name: static analysis (legacy)

on:
  push:
    branches:
    - master
    - main
  workflow_dispatch:
  repository_dispatch:

jobs:
  scan:
    uses: ibm-skills-network/.github/.github/workflows/appscan-legacy.yml@main
    secrets:
      skills-network-bot-app-id: ${{ secrets.SKILLS_NETWORK_BOT_APP_ID }}
      skills-network-bot-private-key: ${{ secrets.SKILLS_NETWORK_BOT_PRIVATE_KEY }}
      asoc-key: ${{ secrets.ASOC_KEY }}
      asoc-secret: ${{ secrets.ASOC_SECRET }}
